name: libyear
version: 0.0.1
environment:
  sdk: '^3.0.0-89.0.dev'
dependencies:
  args: ^2.3.1
  collection: ^1.17.0
  http: ^0.13.5
  pub_semver: ^2.1.3
  yaml: 3.1.0
dev_dependencies:
  path: ^1.8.3
  shelf: ^1.4.0
  test: ^1.22.2
  test_descriptor: ^2.0.1
